apiVersion: v1
kind: ServiceAccount
metadata:
  name: rick-morty-app
  namespace: rick-morty-app
  labels:
    app.kubernetes.io/name: rick-morty-app
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rick-morty-app
  namespace: rick-morty-app
  labels:
    app.kubernetes.io/name: rick-morty-app
    app.kubernetes.io/component: role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rick-morty-app
  namespace: rick-morty-app
  labels:
    app.kubernetes.io/name: rick-morty-app
    app.kubernetes.io/component: rolebinding
subjects:
- kind: ServiceAccount
  name: rick-morty-app
  namespace: rick-morty-app
roleRef:
  kind: Role
  name: rick-morty-app
  apiGroup: rbac.authorization.k8s.io
