{{- if .Values.sidecar.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rick-morty-app.fullname" . }}-fluentd-config
  labels:
    {{- include "rick-morty-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: logging
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/app/*.log
      pos_file /var/log/fluentd-app.log.pos
      tag app.logs
      format json
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      time_key timestamp
      keep_time_key true
    </source>

    <filter app.logs>
      @type record_transformer
      <record>
        hostname "#{Socket.gethostname}"
        namespace {{ .Release.Namespace }}
        app {{ include "rick-morty-app.name" . }}
        release {{ .Release.Name }}
      </record>
    </filter>

    <match app.logs>
      @type forward
      <server>
        name elasticsearch
        host elasticsearch
        port 24224
        weight 60
      </server>
      <buffer>
        @type file
        path /var/log/fluentd-buffers/app.buffer
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 2
        flush_interval 5s
        retry_forever
        retry_max_interval 30
        chunk_limit_size 2M
        queue_limit_length 8
        overflow_action block
      </buffer>
    </match>
{{- end }}
