apiVersion: v1
kind: Service
metadata:
  name: {{ include "rick-morty-app.fullname" . }}
  labels:
    {{- include "rick-morty-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.targetPort }}"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rick-morty-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
